apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: aws-ebs-csi-driver
  namespace: flux-system
spec:
  interval: 1h
  url: https://github.com/kubernetes-sigs/aws-ebs-csi-driver
  ref:
    branch: release-1.28
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: aws-ebs-csi
  namespace: flux-system
spec:
  interval: 1h
  sourceRef:
    kind: GitRepository
    name: aws-ebs-csi-driver
  path: ./deploy/kubernetes/overlays/stable
  prune: true
  targetNamespace: kube-system
