apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 1h
  chart:
    spec:
      chart: cilium
      version: "1.16.x"
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: kube-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    kubeProxyReplacement: true
    gatewayAPI:
      enabled: true
    ipam:
      operator:
        clusterPoolIPv4PodCIDRList:
          - "${POD_CIDR}"
    hubble:
      enabled: true
      relay:
        enabled: true
      ui:
        enabled: true
