apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-operator
  namespace: flux-system
spec:
  interval: 1h
  url: https://github.com/controlplaneio-fluxcd/flux-operator
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-operator
  namespace: flux-system
spec:
  interval: 1h
  sourceRef:
    kind: GitRepository
    name: flux-operator
  path: ./config/default
  prune: true
  patches:
    - target:
        kind: Deployment
        name: flux-operator
      patch: |
        - op: add
          path: /spec/template/spec/tolerations
          value:
            - key: node-role.kubernetes.io/control-plane
              operator: Exists
              effect: NoSchedule
            - key: node.cloudprovider.kubernetes.io/uninitialized
              operator: Exists
              effect: NoSchedule
