apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-instance
  namespace: flux-system
spec:
  interval: 1h
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./fluxsetup/flux-instance
  prune: true
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
